saveExact: true
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true
trustPolicy: "no-downgrade"
allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@vitest/mocker@5.0.0"
  - "@vitest/spy@5.0.0"
  - rolldown-plugin-dts@0.28.5
  - tsdown@0.23.0
  - vitest@5.0.0
